stages:
  - androidbuild
  - androidtest

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/MainApplication/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend/MainApplication
    - ./gradlew build --stacktrace --info --scan
  artifacts:
    paths:
      - Android_test/app/build/outputs/

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/MainApplication/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend/MainApplication
    - ./gradlew test
